# ============================================
# AWS BATCH INFRASTRUCTURE - CloudFormation
# ============================================

AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS Batch infrastructure for auto-scaling video processing workers.
  Part of the Scalable Short Video App thesis project.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where Batch instances will run

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs for Batch compute environment (use private subnets)

  ECRImageUri:
    Type: String
    Description: ECR image URI for video-worker-service
    Default: ''

  RabbitMQUrl:
    Type: String
    Description: RabbitMQ connection URL
    Default: amqp://user:password@rabbitmq:5672
    NoEcho: true

  DBHost:
    Type: String
    Description: MySQL database host

  DBPort:
    Type: String
    Default: '3306'

  DBUsername:
    Type: String
    Default: admin

  DBPassword:
    Type: String
    NoEcho: true

  DBName:
    Type: String
    Default: short_video_db

  S3Bucket:
    Type: String
    Description: S3 bucket for video storage

  AWSRegion:
    Type: String
    Default: ap-southeast-1

  AWSAccessKeyId:
    Type: String
    NoEcho: true

  AWSSecretAccessKey:
    Type: String
    NoEcho: true

  VideoServiceUrl:
    Type: String
    Default: http://video-service:3002
    Description: URL of video-service for cache invalidation

  CloudFrontUrl:
    Type: String
    Default: ''
    Description: CloudFront distribution URL for serving videos (e.g. https://d3ucy55nukq6p9.cloudfront.net)

  MaxvCpus:
    Type: Number
    Default: 16
    Description: Maximum vCPUs for the compute environment

Resources:
  # ============================================
  # SECURITY GROUP
  # ============================================
  # Allows outbound traffic for:
  # - RabbitMQ (5672)
  # - MySQL (3306)
  # - S3/ECR (443)
  # - Video Service (3002)
  # ============================================
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for AWS Batch video workers
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound (worker needs to reach RabbitMQ, S3, DB)
      Tags:
        - Key: Name
          Value: short-video-batch-sg
        - Key: Project
          Value: short-video-app

  # ============================================
  # IAM ROLES
  # ============================================
  
  # Role for AWS Batch service itself
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: short-video-batch-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  # Role for EC2 instances that run the containers
  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: short-video-batch-instance-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BatchInstanceRole

  # Role for the container (ECS Task Role)
  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: short-video-batch-job-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3Bucket}'
                  - !Sub 'arn:aws:s3:::${S3Bucket}/*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: RekognitionAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:DetectLabels
                Resource: '*'

  # ============================================
  # COMPUTE ENVIRONMENT
  # ============================================
  # Uses EC2 Spot instances for cost savings (up to 90% cheaper)
  # Automatically provisions/terminates instances based on job queue
  # ============================================
  VideoProcessingComputeEnv:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: short-video-processing-env
      Type: MANAGED
      State: ENABLED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: SPOT
        # ============================================
        # SPOT PRICING
        # ============================================
        # BidPercentage: Max price as % of On-Demand price
        # 60% means you pay at most 60% of On-Demand
        # If Spot price exceeds this, instance is terminated
        # (worker handles graceful shutdown via SIGTERM)
        # ============================================
        BidPercentage: 60
        SpotIamFleetRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-ec2-spot-fleet-tagging-role'
        MinvCpus: 0          # Scale to zero when no jobs (no cost!)
        MaxvCpus: !Ref MaxvCpus
        DesiredvCpus: 0       # Start with 0, scale up on demand
        InstanceTypes:
          - c5.large    # 2 vCPU, 4 GB - good for FFmpeg
          - c5.xlarge   # 4 vCPU, 8 GB - for heavy videos
          - m5.large    # 2 vCPU, 8 GB - balanced
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        Subnets: !Ref SubnetIds
        Tags:
          Project: short-video-app
          Component: video-processing

  # ============================================
  # JOB QUEUE
  # ============================================
  # Jobs submitted here wait for compute resources
  # Priority: higher number = higher priority
  # ============================================
  VideoProcessingJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: short-video-processing-queue
      State: ENABLED
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref VideoProcessingComputeEnv

  # ============================================
  # JOB DEFINITION
  # ============================================
  # Defines the Docker container configuration for workers
  # Each job runs one instance of video-worker-service
  # ============================================
  VideoWorkerJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: short-video-worker
      Type: container
      RetryStrategy:
        Attempts: 2   # Retry once on failure (Spot interruption, etc.)
      Timeout:
        AttemptDurationSeconds: 1800  # 30 minutes max per job
      ContainerProperties:
        Image: !Ref ECRImageUri
        # ============================================
        # RESOURCE ALLOCATION
        # ============================================
        # Video encoding is CPU-intensive
        # 2 vCPU + 3 GB is enough for 720p ABR encoding
        # ============================================
        Vcpus: 2
        Memory: 3072    # 3 GB
        JobRoleArn: !GetAtt BatchJobRole.Arn
        Environment:
          - Name: NODE_ENV
            Value: production
          - Name: BATCH_MODE
            Value: 'true'
          - Name: AUTO_EXIT_WHEN_IDLE
            Value: 'true'
          - Name: IDLE_TIMEOUT_SECONDS
            Value: '60'
          - Name: WORKER_CONCURRENCY
            Value: '2'
          # Database
          - Name: DB_HOST
            Value: !Ref DBHost
          - Name: DB_PORT
            Value: !Ref DBPort
          - Name: DB_USERNAME
            Value: !Ref DBUsername
          - Name: DB_PASSWORD
            Value: !Ref DBPassword
          - Name: DB_DATABASE
            Value: !Ref DBName
          # RabbitMQ
          - Name: RABBITMQ_URL
            Value: !Ref RabbitMQUrl
          - Name: RABBITMQ_QUEUE
            Value: video_processing_queue
          # AWS S3
          - Name: AWS_ACCESS_KEY_ID
            Value: !Ref AWSAccessKeyId
          - Name: AWS_SECRET_ACCESS_KEY
            Value: !Ref AWSSecretAccessKey
          - Name: AWS_REGION
            Value: !Ref AWSRegion
          - Name: AWS_S3_BUCKET
            Value: !Ref S3Bucket
          # CloudFront
          - Name: CLOUDFRONT_URL
            Value: !Ref CloudFrontUrl
          # Video Service
          - Name: VIDEO_SERVICE_URL
            Value: !Ref VideoServiceUrl
          # Paths (inside container)
          - Name: UPLOAD_ROOT_PATH
            Value: /app
          - Name: RAW_VIDEOS_PATH
            Value: uploads/raw_videos
          - Name: PROCESSED_VIDEOS_PATH
            Value: uploads/processed_videos
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: /aws/batch/short-video-worker
            awslogs-region: !Ref AWSRegion
            awslogs-stream-prefix: batch

  # ============================================
  # CLOUDWATCH LOG GROUP
  # ============================================
  BatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/batch/short-video-worker
      RetentionInDays: 7   # Keep logs for 7 days (save cost)

# ============================================
# OUTPUTS
# ============================================
# These values are needed in the video-service .env file
# ============================================
Outputs:
  JobQueueArn:
    Description: ARN of the Batch Job Queue (set as AWS_BATCH_JOB_QUEUE)
    Value: !Ref VideoProcessingJobQueue
    Export:
      Name: !Sub '${AWS::StackName}-JobQueueArn'

  JobDefinitionArn:
    Description: ARN of the Job Definition (set as AWS_BATCH_JOB_DEFINITION)
    Value: !Ref VideoWorkerJobDefinition
    Export:
      Name: !Sub '${AWS::StackName}-JobDefinitionArn'

  ComputeEnvironmentArn:
    Description: ARN of the Compute Environment
    Value: !Ref VideoProcessingComputeEnv

  SecurityGroupId:
    Description: Security Group ID for Batch instances
    Value: !Ref BatchSecurityGroup

  Usage:
    Description: How to use these outputs
    Value: !Sub |
      Add to video-service .env:
      AWS_BATCH_JOB_QUEUE=${VideoProcessingJobQueue}
      AWS_BATCH_JOB_DEFINITION=${VideoWorkerJobDefinition}
